name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: dotnet test --filter Category!=LocalTest
    - if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet publish
    - if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v3
      with:
        name: RaceDirector
        path: src/RaceDirector/bin/Debug/net6.0/publish/**
        if-no-files-found: error
